services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    volumes:
      - caddy-data:/data
    ports:
      - '80:80'
      - '443:443'
    networks:
      - backend
    command: caddy reverse-proxy --from ${SSL_HOSTNAME} --to owncast:8080
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  owncast:
    image: owncast/owncast:0.1.13
    container_name: owncast
    volumes:
      - owncast-data:/app/data
    ports:
      - '1935:1935'
    networks:
      - backend
    command: -streamkey ${STREAM_KEY} -adminpassword ${ADMIN_PASSWORD}
    restart: unless-stopped
    expose:
      - 8080

networks:
  backend:
    name: owncast_backend

volumes:
  caddy-data:
    name: owncast_caddy_data
  owncast-data:
    name: owncast_data
