name: zwtv-owncast
services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    volumes:
      - caddy-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    networks:
      - backend
    command: caddy reverse-proxy --from ${SSL_HOSTNAME} --to owncast:8080
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
  owncast:
    image: owncast/owncast:0.1.3
    container_name: owncast
    volumes:
      - owncast-data:/app/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '0.0.0.0:1935:1935'
    networks:
      - backend
    command: -streamkey ${STREAM_KEY} -adminpassword ${ADMIN_PASSWORD}
    restart: unless-stopped
    expose:
      - '8080'
networks:
  backend:
    name: owncast_backend
volumes:
  caddy-data:
    name: owncast_caddy_data
  owncast-data:
    name: owncast_data
