name: linter

on:
  pull_request:
  push:
    branches: 
      - main
    paths: 
      - '**.sh'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ShellCheck on all .sh files
        uses: azohra/shell-linter@latest
